# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/akutz/gotil"
  version = "0.1.0"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.13.7"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/meatballhat/negroni-logrus"

[[constraint]]
  name = "github.com/open-policy-agent/opa"
  version = "0.9.2"

[[constraint]]
  name = "github.com/ory/go-convenience"
  version = "0.0.6"

[[constraint]]
  name = "github.com/ory/graceful"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ory/herodot"
  version = "0.4.1"

[[constraint]]
  name = "github.com/ory/ladon"
  version = "0.8.10"

[[constraint]]
  name = "github.com/ory/pagination"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ory/sqlcon"
  version = "0.0.7"

[[constraint]]
  branch = "master"
  name = "github.com/ory/x"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/go-resty/resty.v0"
  version = "0.13.0"

[prune]
  go-tests = true
  unused-packages = true
